### ISSUE TITLE
Error in FUN(X[[i]], ...) : subscript out of bounds

### ISSUE THREAD

**Issue by oguienko** [gloewing/photometry_FLMM#3]
Hello! I have just started getting into this awesome package, and I have encountered a problem. I have run the same code on two different datasets, and for one of them, it is working beautifully. On the other one, it gives the following error:

```
3.
lapply(massmm, "[[", "aic")
2.
do.call(c, lapply(massmm, "[[", "aic"))
1.
fui(photometry ~ cs + (1 | ID), data = dat, parallel = TRUE)
```

My code:
```
dat = read.csv("./low_coc_df_zall.csv") # read in data
mod1 = fui(photometry ~ cs + (1 | ID), data = dat, parallel = TRUE)
```

The only significant difference between the datasets is that the latter one is tiny - I only have one trial and one session per animal due to experimental constraints. Is this the issue, or can it be something else?

Here is the dataset:
[df.csv](https://github.com/user-attachments/files/17226942/df.csv)

**Comment by gloewing** [comment]
Thanks for reaching out! You are correct: the reason fui() is not working
on this dataset is because you only have 1 trial per animal. Functional
mixed models are for analyses with multiple trials per animal (it's like
the repeated measures version of a functional regression). When you only
have one observation per animal you can fit a functional linear model,
instead of a functional linear *mixed* model. I have examples of this in
the eLife paper and you can find the code here (see line 182 where I fit
the model and then plot the results):

https://github.com/gloewing/photometry_FLMM/blob/main/Figures/Appendix_DA_Adapts/da_adapts_learn_fReg.R

Let me know if you have any other questions and good luck!

Best,
Gabe

**Comment by oguienko** [comment]
This is great, thank you so much!
